/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConformiteRouteImport } from './routes/conformite'
import { Route as ExplicabiliteRouteImport } from './routes/explicabilite'
import { Route as LotsRouteImport } from './routes/lots'
import { Route as SimulateurRouteImport } from './routes/simulateur'
import { Route as DevisIndexRouteImport } from './routes/devis.index'
import { Route as DevisReferenceRouteImport } from './routes/devis.$reference'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConformiteRoute = ConformiteRouteImport.update({
  id: '/conformite',
  path: '/conformite',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplicabiliteRoute = ExplicabiliteRouteImport.update({
  id: '/explicabilite',
  path: '/explicabilite',
  getParentRoute: () => rootRouteImport,
} as any)
const LotsRoute = LotsRouteImport.update({
  id: '/lots',
  path: '/lots',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateurRoute = SimulateurRouteImport.update({
  id: '/simulateur',
  path: '/simulateur',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisIndexRoute = DevisIndexRouteImport.update({
  id: '/devis/',
  path: '/devis/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisReferenceRoute = DevisReferenceRouteImport.update({
  id: '/devis/$reference',
  path: '/devis/$reference',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conformite': typeof ConformiteRoute
  '/explicabilite': typeof ExplicabiliteRoute
  '/lots': typeof LotsRoute
  '/simulateur': typeof SimulateurRoute
  '/devis/$reference': typeof DevisReferenceRoute
  '/devis/': typeof DevisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conformite': typeof ConformiteRoute
  '/explicabilite': typeof ExplicabiliteRoute
  '/lots': typeof LotsRoute
  '/simulateur': typeof SimulateurRoute
  '/devis/$reference': typeof DevisReferenceRoute
  '/devis': typeof DevisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conformite': typeof ConformiteRoute
  '/explicabilite': typeof ExplicabiliteRoute
  '/lots': typeof LotsRoute
  '/simulateur': typeof SimulateurRoute
  '/devis/$reference': typeof DevisReferenceRoute
  '/devis/': typeof DevisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conformite'
    | '/explicabilite'
    | '/lots'
    | '/simulateur'
    | '/devis/$reference'
    | '/devis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conformite'
    | '/explicabilite'
    | '/lots'
    | '/simulateur'
    | '/devis/$reference'
    | '/devis'
  id:
    | '__root__'
    | '/'
    | '/conformite'
    | '/explicabilite'
    | '/lots'
    | '/simulateur'
    | '/devis/$reference'
    | '/devis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConformiteRoute: typeof ConformiteRoute
  ExplicabiliteRoute: typeof ExplicabiliteRoute
  LotsRoute: typeof LotsRoute
  SimulateurRoute: typeof SimulateurRoute
  DevisReferenceRoute: typeof DevisReferenceRoute
  DevisIndexRoute: typeof DevisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conformite': {
      id: '/conformite'
      path: '/conformite'
      fullPath: '/conformite'
      preLoaderRoute: typeof ConformiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explicabilite': {
      id: '/explicabilite'
      path: '/explicabilite'
      fullPath: '/explicabilite'
      preLoaderRoute: typeof ExplicabiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lots': {
      id: '/lots'
      path: '/lots'
      fullPath: '/lots'
      preLoaderRoute: typeof LotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulateur': {
      id: '/simulateur'
      path: '/simulateur'
      fullPath: '/simulateur'
      preLoaderRoute: typeof SimulateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis/': {
      id: '/devis/'
      path: '/devis'
      fullPath: '/devis/'
      preLoaderRoute: typeof DevisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis/$reference': {
      id: '/devis/$reference'
      path: '/devis/$reference'
      fullPath: '/devis/$reference'
      preLoaderRoute: typeof DevisReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConformiteRoute: ConformiteRoute,
  ExplicabiliteRoute: ExplicabiliteRoute,
  LotsRoute: LotsRoute,
  SimulateurRoute: SimulateurRoute,
  DevisReferenceRoute: DevisReferenceRoute,
  DevisIndexRoute: DevisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
